### ISSUE TITLE
Does it extract images too?

### ISSUE THREAD

**Issue by debdarsan** [ping543f/pdf-extraction-tool-comparison#4]
Dear Miah,

Thank you for your very informatic article! I'm sure it will help me in processing pdfs.

Can you please send me the code and data?

Thanks in Advance!

Regards,
Debdarsan

**Comment by ping543f** [comment]
Thank you Dr Debdarsan Niyogi,
Please share your email, so that I can share the codes and dataset

**Comment by debdarsan** [comment]
Thank you for your response!

My email address is:

***@***.***

Regards,
Debdarsan

**Comment by ping543f** [comment]
Hi, your email address is not visible. please send me an email to ping543f@gmail.com
